### ISSUE TITLE
tapedoc typos

### ISSUE THREAD

**Issue by svigerske** [coin-or/ADOL-C#9] opened 2020-02-22 13:40 UTC
Issue created by migration from Trac.

Original creator: rucarden

Original creation time: 2012-01-25 20:59:06

Assignee: @awalther1

Version: 2.0

Keywords: tapedoc

Noticed the following typo while testing out the extern_fctn features.  It leads to tex files that do not compile on account of the underscore and the missing comma.
107,108c107,108
<                        "extern fctn"
<                        "ignore_me"
---
>                        "extern fctn",
>                        "ignore\\_me"

The following typo leads to their being too few columns on the second line of the table produced by tapedoc.  
141c141,142
<     fprintf(fp," %i & start of tape & & & & & & & & & &  \\\\ \\hline \n",opcode);
---
>     fprintf(fp," %i & %i & %i & start of tape & & & & & & & & & & \\\\ \\hline \n",op_cnt, rev_op_cnt,opcode);
> 
145c146
<     fprintf(fp," %i & start of tape & & & & & & & \\\\ \\hline \n",opcode);
---
>     fprintf(fp," %i & %i & %i & start of tape & & & & & & & \\\\ \\hline \n",op_cnt, rev_op_cnt,opcode);

**Comment by awalther1** [comment] 2020-03-31 12:49
difficult to reproduce since files changed a lot since then, should be fixed

**Closed by awalther1** 2020-03-31 12:49 UTC
Labels: bug, libadolc, minor
